name: "install uv"
description: "Install uv for python, using community action"
runs:
  using: "composite"
  steps:
    - name: install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh